### ISSUE TITLE
Update for MapLibre Native Android 11.0.0

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-navigation-android#104]
[MapLibre Native Android 11.0.0](https://github.com/maplibre/maplibre-native/releases/tag/android-v11.0.0-pre0) has different import paths. Does anyone volunteer to update this package?

**Comment by Fabi755** [comment]
When we doing this, we should thinking about to upgrade our package names as well.

What do you think @boldtrn?

**Comment by boldtrn** [comment]
Yes I think we should update our naming as well. Both for classes as well as packages 👍

**Comment by Fabi755** [comment]
I will finish the route eating this or next week. After that I will continue with this task.

**Comment by boldtrn** [comment]
It might be a good idea to do this in two steps. First update to the latest 10.X and create a release for this. Then we update to 11 and create a major release with breaking changes.

Android 11 requires OpenGL 3 which not everyone wants. To overhead for the additional release should be rather minimal as I don't think there were a lot of serious changes in the 10.X release.

**Comment by nitrag** [comment]
Hi, what's the status on this?

**Comment by Fabi755** [comment]
The other ticket takes too long, I will prefer this change here.

> Android 11 requires OpenGL 3 which not everyone wants. To overhead for the additional release should be rather minimal as I don't think there were a lot of serious changes in the 10.X release.

I see that the native repository also have an legacy `10.x.x` branch. I think we should also do that, to support fixes of the native library?!

**Comment by boldtrn** [comment]
Yes I would propose that we first update to the latest version 10.x.x and do a release, then we do another breaking release with v11.
