### ISSUE TITLE
Puck indicator is not keeping up with the device actual location

### ISSUE THREAD

**Issue by javaherisaber** [maplibre/maplibre-navigation-android#108]
**Android API:** 26-33
**Maplibre Navigation SDK version:** 3.0.0

When driving to a destination, the Puck (MyLocation) indicator is getting behind the current device location
which is misleading during navigation
for example, I get past an intersection in real, but the map shows 10-20 meters behind

<img src="https://github.com/maplibre/maplibre-navigation-android/assets/29440700/395c7c84-1cb7-4c95-a4e7-6b5b5c46d10a" width="256" height="455">

**Comment by Fabi755** [comment]
This is a known problem of the [MapLibre native project](https://github.com/maplibre/maplibre-native).

The biggest problem is the implementation of the animation for the movement of the puck.

If you are using the raw GPS information, the puck is jumping and moves jerkily every second to the current position. For a smooth view, the puck is animated. This animation is calculated from the last position to the newest position. The duration is calculated also for a second. When the animation ends, the puck is then on the current location. But the real location has also moved forward and is not no longer up to date. 

With this implementation the location puck is always a step behind. A solution were to use the current position as start point and calculate the most probable future point. @boldtrn has mentioned the *Kalman filter* for this.

Feel free to start working and create a PR for this topic :-)

**Comment by Fabi755** [comment]
Closed. Not part of the navigation project.

**Comment by javaherisaber** [comment]
@Fabi755 @boldtrn 
Please give me some clues on where to start.
Should I work on the [MapLibre native project](https://github.com/maplibre/maplibre-native) or are other projects involved in this change?

**Comment by boldtrn** [comment]
Yes, if you would like to improve the Puck, maplibre  native is the right place. You might want to join the Slack if you are having issues getting started.
