### ISSUE TITLE
Maplibre navigation

### ISSUE THREAD

**Issue by viktorgt** [maplibre/maplibre-navigation-android#11]
Hi, 
first, many thanks for providing the fork. 
In [our fork](https://github.com/sw-code/flitsmeister-navigation-android) of flitsmeister we added navigation-ui and ported it from Mapbox to Maplibre.

There is also an ongoing discussion about the state of maplibre navigation: https://github.com/maplibre/maplibre-navigation-android/issues/8
Is this interesting for you? It would be great if we could establish a real alternative to mapbox.

**Comment by phal0r** [comment]
@viktorgt Out of curiosity: Do you plan to maintain your fork for longer time? I am currently screening the options for maps integration (including navigation)

**Comment by hmtriit** [comment]
hi @viktorgt plugin maplibre-navigation-android dependency with mapbox-direction
we can omit it or have another alternative, etc... ?

**Comment by boldtrn** [comment]
@viktorgt contributions would be very welcome and I would be happy to review PRs. 

@wipfli are there any reasons we should not add the Navigation-UI back to this repo?

**Comment by wipfli** [comment]
I have no clue. @thehoneymad?

**Comment by thehoneymad** [comment]
I don't see a reason not to. But also would be nice to see the addition of navigation-ui in a screenshot.

**Comment by boldtrn** [comment]
@wipfli @thehoneymad @Brammos there is a new PR for this, see #51
