### ISSUE TITLE
Make InstructionView usable in custom activity

### ISSUE THREAD

**Issue by Trietes** [maplibre/maplibre-navigation-android#117]
I would like to use the InstructionView (https://github.com/maplibre/maplibre-navigation-android/blob/main/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/instruction/InstructionView.java)  in a custom Activity. I think its a quiet good component to start with when having a custom ui.

The problem is that it is tightly bound to the NavigationViewModel via the subscribe function. I think it would be a good idea to de-couple it, so it can be used in other view models. 

The easiest way that comes to my mind would be having an interface which provides all the needed live data values to update the InstructionView. The subscribe function could now use the interface instead of the NavigationViewModel. This would allow any view model implementing the interface and then subscribing the the InstructionView. 

Does anybody have an opinion on this? I would be willing to do a pull request on this.

**Comment by Fabi755** [comment]
> The problem is that it is tightly bound to the NavigationViewModel via the subscribe function

You can use this also without the view model.
Add the view to your layout, and update the instruction by the route progress callback & milestone event callback.


```xml
    <com.mapbox.services.android.navigation.ui.v5.instruction.InstructionView
        android:id="@+id/mapInstruction"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_margin="8dp" />
```

```kotlin

// Activity / Fragment fields
private val progressChangeListener = ProgressChangeListener { location, routeProgress ->
    binding.mapInstruction.updateDistance(routeProgress)
}

private val milestoneEventListener = MilestoneEventListener { _, _, milestone ->
    binding.mapInstruction.updateInstructions(milestone)
}

// onCreated & mapReady:
MapboxNavigation(
            requireContext(),
            MapboxNavigationOptions.builder()
                .enableOffRouteDetection(true)
                .snapToRoute(true)
                .build()
        )
            .apply {
                addProgressChangeListener(progressChangeListener)
                addMilestoneEventListener(milestoneEventListener)
            }
```

---

> The easiest way that comes to my mind would be having an interface which provides all the needed live data values to update the InstructionView. The subscribe function could now use the interface instead of the NavigationViewModel. This would allow any view model implementing the interface and then subscribing the the InstructionView.
> 
> Does anybody have an opinion on this? I would be willing to do a pull request on this.

Feel free to adapt and improve it anyway, if you don't like the current solution. If the above described solution is enough, a updated class description would maybe help.

**Comment by Trietes** [comment]
Hug

**Comment by Trietes** [comment]
Huge thanks for the quick reply!
I just gave it a quick try and it did work. I think subscribing to the view is a nice way, but its not worth introducing another interface if there is a simple way of updating the instruction view via the mentioned functions.

An example activity in the example app would've helped me. Maybe I'll find some time to add one and do a PR on it, but I'm quiet busy right now. I'll close this one for now. Thanks!
