### ISSUE TITLE
Android Studio Emulator Crash

### ISSUE THREAD

**Issue by ccritne** [maplibre/maplibre-navigation-android#130]
Settings device emulator:

API: 35
Graphics: Hardware
RAM: 8GB
VM: 1GB
InternalStorage: 20GB
SD: No

Crash on this 
> FATAL EXCEPTION: main
>  Process: org.maplibre.navigation.android.example, PID: 2779
>                                                                                                     java.lang.RuntimeException: Unable to start service org.maplibre.navigation.android.navigation.v5.navigation.NavigationService@7372331 with null: java.lang.NullPointerException: Parameter specified as non-null is null: method org.maplibre.navigation.android.navigation.v5.navigation.NavigationService.onStartCommand, parameter intent
>                                                                                                     	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5165)
>                                                                                                     	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
>                                                                                                     	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2469)
>                                                                                                     	at android.os.Handler.dispatchMessage(Handler.java:107)
>                                                                                                     	at android.os.Looper.loopOnce(Looper.java:232)
>                                                                                                     	at android.os.Looper.loop(Looper.java:317)
>                                                                                                     	at android.app.ActivityThread.main(ActivityThread.java:8705)
>                                                                                                     	at java.lang.reflect.Method.invoke(Native Method)
>                                                                                                     	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
>                                                                                                     	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
>                                                                                                     Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method org.maplibre.navigation.android.navigation.v5.navigation.NavigationService.onStartCommand, parameter intent
>                                                                                                     	at org.maplibre.navigation.android.navigation.v5.navigation.NavigationService.onStartCommand(Unknown Source:2)
>                                                                                                     	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5147)
>                                                                                                     	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0) 
>                                                                                                     	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2469) 
>                                                                                                     	at android.os.Handler.dispatchMessage(Handler.java:107) 
>                                                                                                     	at android.os.Looper.loopOnce(Looper.java:232) 
>                                                                                                     	at android.os.Looper.loop(Looper.java:317) 
>                                                                                                     	at android.app.ActivityThread.main(ActivityThread.java:8705) 
>                                                                                                     	at java.lang.reflect.Method.invoke(Native Method) 
>                                                                                                     	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580) 
>                                                                                                     	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)

**Comment by Fabi755** [comment]
The crash on the Emulator is caused by the native logic in MapLibre native, or the depending engines. Please use a real device for now.

Your posted stacktrace is not the cause for the crash, it's more a sub-crash of the navigation services, that is caused by the main cause. If you scroll up in your logs, you will find a native crash error.

**Comment by Fabi755** [comment]
See: https://github.com/maplibre/maplibre-native/issues/2371

**Comment by ccritne** [comment]
Ty. I have same logs. For now I use real device but it's so annoying :(
