### ISSUE TITLE
Access token validation

### ISSUE THREAD

**Issue by m7mdra** [maplibre/maplibre-navigation-android#16]
**Android API:** 30
**Maplibre Navigation SDK version:** 1.1.1

### Steps to trigger behavior

 1. use example project
 2. use access token without any of the prefixes `pk.`, `sk.` or `tk.`
 3. app crashes with `  com.mapbox.core.exceptions.ServicesException: Using Mapbox Services requires setting a valid access token.`

### Expected behavior
map directions should send the find route request
### Actual behavior
app crashing with validation error

**Comment by m7mdra** [comment]
after investigating the problem i found that its related to sdk-service rather than navigation.

**Comment by hmtriit** [comment]
The same issue, I think plugin maplibre-navigation dependency with mapbox-sdk-direction.

**Comment by JonasVautherin** [comment]
I am having the same issue. How did you solve it?

**Comment by boldtrn** [comment]
The latest version does not require a Mapbox SDK key.  Also see this discussion: https://github.com/maplibre/maplibre-navigation-android/discussions/101

**Comment by JonasVautherin** [comment]
@boldtrn: I am afraid I did not understand that. What latest version do you mean? I am having the "com.mapbox.core.exceptions.ServicesException: Using Mapbox Services requires setting a valid access token" running this example app, with what I believe are the [latest versions](https://github.com/maplibre/maplibre-navigation-android/blob/main/gradle/dependencies.gradle#L12-L14).

Which version exactly should I update to prevent this error?

**Comment by JonasVautherin** [comment]
The solution is to prefix `pk.` to the access token (even if it is e.g. a Graphhopper token).
