### ISSUE TITLE
org.gradle.internal.resolve.ModuleVersionNotFoundException

### ISSUE THREAD

**Issue by danilo80** [maplibre/maplibre-navigation-android#17]
Hi, when i add  implementation 'com.github.flitsmeister:flitsmeister-navigation-android:v1.1.1' i get these errors:

org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':app:mitDebugCompileClasspath'.

org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.github.flitsmeister:flitsmeister-navigation-android:v1.1.1.

**Comment by imranMnts** [comment]
Use 

```
implementation "com.github.flitsmeister:flitsmeister-navigation-android:1.1.1"
```

instead of

```
implementation "com.github.flitsmeister:flitsmeister-navigation-android:v1.1.1"
```
