### ISSUE TITLE
Update CHANGELOG

### ISSUE THREAD

**Issue by boldtrn** [maplibre/maplibre-navigation-android#24]
Currently the CHANGELOG.md is outdated, we should at least include the latest release to start adding all changes from now on.

**Comment by boldtrn** [comment]
Fixed by https://github.com/maplibre/maplibre-navigation-android/commit/41218bdb923a3ceeac68a6d053c8fd3110f53ab6

**Comment by wipfli** [comment]
You can also use `Fixes #24` in the pull request description, then GitHub closes the issues automatically once the pull request is merge...
