### ISSUE TITLE
Question for the future support of Maplibre Navigation SDK 

### ISSUE THREAD

**Issue by jDilshodbek** [maplibre/maplibre-navigation-android#34]
Hello guys. I am checking MapLibre navigation SDK .It seems Libre version is forked from MapBox v9. It is expected to shutdown support on April 4, 2023. My question is, does Maplibre stop as well if they stop supporting? or will you have any plans with v10 with paid services?

**Comment by boldtrn** [comment]
This library is developed independently from Mapbox. You can use other routing and map tile providers than Mapbox.

**Comment by jDilshodbek** [comment]
So does it mean you will not regulary get updates from Mapbox?

**Comment by boldtrn** [comment]
No, I think the overall goal is to be as independent from Mapbox as possible. 

> MapLibre started as an open-source fork of the popular Mapbox rendering libraries after their switch to a proprietary license in December 2020.
https://maplibre.org/about/

This library is developed 100% open source.

**Comment by jDilshodbek** [comment]
Thank you for your response. I think everything is clear for me right now, and I am  going to close this issue since it is just only question
