### ISSUE TITLE
How decode geometries of DirectionsRoutes in Points?

### ISSUE THREAD

**Issue by moiatto** [maplibre/maplibre-navigation-android#35]
Hi Guys,
I'm new here.

Can anyone tell me how decode geometries of DirectionsRoutes in Points? Because I want to convert them to display in another mapView (Mapsforge VTM).

I have seen this object DecodeUtils from MapBox package com.mapbox.navigation.base.utils.
fun DirectionsRoute.completeGeometryToPoints: List(Point)

Thanks
Andrew

**Comment by boldtrn** [comment]
Depends how they are encoded. You can experiment with `PolylineUtils.decode`.

**Comment by moiatto** [comment]
So I obtain the routes:
`List<DirectionsRoute> routes = response.body().routes();`
then I convert with PolylineUtils.decode
`List<Point> pointsFromResponse = PolylineUtils.decode(route.geometry(),6);`

Work perfect!

Another small question...how can manage and update info (total distance and duration) when I follow the route?
Where I can see?

Thanks
Andrew

**Comment by boldtrn** [comment]
Right now this library does not come with a prebuild UI. You would have to build your own UI. You can get the information from the route progress.
