### ISSUE TITLE
Update to v1.2.0

### ISSUE THREAD

**Issue by moiatto** [maplibre/maplibre-navigation-android#40]
Sorry for my stupid question...

I'm using the v1.1.1 as described here:
```
Step 1. Add it in your root build.gradle at the end of repositories:

  allprojects {
    repositories {
      ...

      jcenter()   // for Maplibre Navigation SDK for Android v1.1.1

      maven { url 'https://jitpack.io' }
    }
  }
Step 2. Add the dependency

  implementation 'com.github.maplibre:maplibre-navigation-android:1.1.1
```

but if I change the implementation to v1.2.0 I get a lot of compile errors.

can you help me?

**Comment by boldtrn** [comment]
What compiles errors do you see?

BTW: we are planning on releasing a new version soon.

**Comment by moiatto** [comment]
After Sync Project with Gradle Files:

Int the "Build Windows":
Failed to resolve: com.github.maplibre:maplibre-navigation-android:1.2.0

**Comment by boldtrn** [comment]
Ah yes, sorry, I mixed up the releases. Yes, 1.2.0 unfortunately did not land on jitpack, as there were build errors.

You can use this in the meantime if you want (this is a snapshot from main branch):
```
dependencies {
  implementation 'com.github.maplibre:maplibre-navigation-android:-SNAPSHOT'
}
```

**Comment by moiatto** [comment]
I have tried now but it seems start to download no.2 files but after 2 seconds, same error:
```
Download maven-metadata.xml...
Download maplibre-navigation-android--SNAPSHOT.pom
```

then
`Failed to resolve: com.github.maplibre:maplibre-navigation-android:-SNAPSHOT`

**Comment by boldtrn** [comment]
You can see all available options on [Jitpack](https://jitpack.io/#maplibre/maplibre-navigation-android/cbd6e39439), for example:

```
dependencies {
	        implementation 'com.github.maplibre:maplibre-navigation-android:cbd6e39439'
}
```

**Comment by moiatto** [comment]
Perfect! This works
