### ISSUE TITLE
locationComponent.lastKnownLocation always returns null

### ISSUE THREAD

**Issue by jDilshodbek** [maplibre/maplibre-navigation-android#41]
mapBox.locationComponent.lastKnownLocation is always returning null unless manually requesting location update with location engine callback
I am using MapLibre version 1.1.1

**Comment by javaherisaber** [comment]
@jDilshodbek @karussell 
I also have the same issue on Android 13, 
last location is always null

**Comment by Fabi755** [comment]
Can you give me more details, what you try to do, and how you want to access the last location data?

**Comment by javaherisaber** [comment]
@Fabi755 
I just cloned the repo and ran the project, making no changes to it
I reproduced it on an emulator with API 33

**Comment by Fabi755** [comment]
There are no issues with this implementation.

The location component (of maplibre-gl for android) is trying to [get the last known location on initialization](https://github.com/maplibre/maplibre-native/blob/612b256821d379d86e47bd90fc29ccf922b57173/platform/android/MapboxGLAndroidSDK/src/main/java/org/maplibre/android/location/LocationComponent.java#L1252). `last known location` means, that any other app (or your own code) must request and receive a location before. This call is not requesting the current GPS position, only the last one that was fetched.

If you start a fresh installed emulator, there is no previous location data in the system. I don't know what happens by a OS restart.

[The missing last location is logged as error](https://github.com/maplibre/maplibre-native/blob/612b256821d379d86e47bd90fc29ccf922b57173/platform/android/MapboxGLAndroidSDK/src/main/java/org/maplibre/android/location/LocationComponent.java#L1428). Maybe a little too much, but that's all.

To solve this problem, you can open a map app (example Google Maps) before testing the demo app. Or request the location by yourself in your custom app code.
