### ISSUE TITLE
The driving-traffic API does not work

### ISSUE THREAD

**Issue by AndrewKisykP** [maplibre/maplibre-navigation-android#45]
curl --location --request GET 'https://api.maptiler.com/maps/directions/v5/mapbox/driving-traffic/5.550339,52.039176;5.559641,52.041519?access_token=pk.eyJ1IjoiaXZhbm51a29sIiwiYSI6ImNsZGszYmV3eTF1NWEzbnBpNjd5aWRyZngifQ.CgRUbleOH0QkODA54mYutA&alternatives=true&geometries=polyline6&overview=full&steps=true&bearings=%3B&continue_straight=true&annotations=congestion%2Cdistance&language=en&roundabout_exits=true&voice_instructions=true&banner_instructions=true&voice_units=metric&key=45p5VMQdkfaQTsiyN7xW' \
--header 'Authorization: Token ed2f63d7e237415b99cab718fcd15f1d_ff9fc7afd409aa9115b0a52611291eaf72fdc41f06ef6646e2afe848f5f6c763'
![image](https://user-images.githubusercontent.com/123394081/215737135-d45c9072-ea1e-4720-a323-dfb21a9fd7c6.png)

**Comment by boldtrn** [comment]
I am not sure if Maptiler is offering a directions API.

Right now the default should work with OSRM or Mapbox. You should be able to implement custom routing engines, for example GraphHopper. See also #44.
