### ISSUE TITLE
Voice navigation

### ISSUE THREAD

**Issue by IvanNykolPe** [maplibre/maplibre-navigation-android#47]
Can you tell me what is needed for voice navigation? I will add the language to speak and voiceInstructions are included
![image](https://user-images.githubusercontent.com/108887997/219584247-b5e07a98-47cd-41cf-aa0f-82ff46ee2cb6.png)

**Comment by boldtrn** [comment]
You can listen to milestone events and use Android TTS to speak the instructions.

**Comment by boldtrn** [comment]
Voice navigation should work with the navigation-ui
