### ISSUE TITLE
Fix memory leak for NavigationService 

### ISSUE THREAD

**Issue by skienzl** [maplibre/maplibre-navigation-android#52]
I discovered that the navigation lib has a memory leak which is already fixed in the mapbox implementation: 
https://github.com/mapbox/mapbox-navigation-android/issues/275

I think it would be a good idea to adapt those changes to fix the leak. 

I would be up to implement the changes.  
What do you think? Any thoughts why we should not adapt to the new/fixed NavigationService implementation?

**Comment by boldtrn** [comment]
Thanks for looking into this, it this leak exists in our codebase as well, we should definitely fix it 👍. Back then the code was still MIT licensed, so it shouldn't be an issue to use this here.
