### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by thuong281** [maplibre/maplibre-navigation-android#53]
Can you release a new version that used maplibre version v10.0.2 and work with Google location service v21

**Comment by boldtrn** [comment]
There is an open PR for this here: https://github.com/maplibre/maplibre-navigation-android/pull/50

I think it would be good to wait until this PR is merged: https://github.com/maplibre/maplibre-navigation-android/pull/51

**Comment by boldtrn** [comment]
BTW: you can use the current master through Jitpack until the new version is released.

**Comment by thuong281** [comment]
> BTW: you can use the current master through Jitpack until the new version is released.

You mean fork thía repo and publish it with jitpack?

**Comment by boldtrn** [comment]
https://jitpack.io/#maplibre/maplibre-navigation-android/2b93183329

```
dependencies {
	        implementation 'com.github.maplibre:maplibre-navigation-android:2b93183329'
}
```

**Comment by thuong281** [comment]
> https://jitpack.io/#maplibre/maplibre-navigation-android/2b93183329
> 
> ```
> dependencies {
> 	        implementation 'com.github.maplibre:maplibre-navigation-android:2b93183329'
> }
> ```

Okay, thank you

**Comment by boldtrn** [comment]
version 2.0.0 was released

https://github.com/maplibre/maplibre-navigation-android/releases/tag/2.0.0
