### ISSUE TITLE
Mapview not displayed

### ISSUE THREAD

**Issue by cmalex23** [maplibre/maplibre-navigation-android#56]
Trying to use the test app, no map is shown.
I tried adding this style url in all locations: `mapbox://styles/mapbox/streets-v12` and also the access token, with no luck.

### Steps to trigger behavior

 1. Download the latest repo
 2. Start the test app
 3. No map is displayed on either of the 2 screens.

**Comment by boldtrn** [comment]
This repo as well as the other repos in the maplibre organization are developed indepndently fomr Mapbox and special Mapbox notation like `mapbox://styles/mapbox/streets-v12` might not work.

I haven't tried it, but it might work using this endpoint: https://docs.mapbox.com/api/maps/styles/

You can try an older version < v2 or you can try different map providers like:
https://www.maptiler.com/
https://stadiamaps.com/
https://mapilion.com/

As this is not a navigation issue, I will close this here.
