### ISSUE TITLE
Can't use like implementation

### ISSUE THREAD

**Issue by Dandriel** [maplibre/maplibre-navigation-android#61]
**Android API: 33**
**Maplibre Navigation SDK version: 2.0.0**

### Steps to trigger behavior

 1. Use implementation 'com.github.maplibre:maplibre-navigation-android:2.0.0'
 2. No objects after com.mapbox.mapboxsdk.* available 

### Expected behavior
Have access to, for example, com.mapbox.mapboxsdk.Mapbox.
### Actual behavior
Have no access to classes.
But inside example with this libraries is work perfect.

**Comment by Fabi755** [comment]
Do you added the `maven { url 'https://jitpack.io' }` part?

**Comment by Dandriel** [comment]
After I add 
```
implementation ('org.maplibre.gl:android-sdk:10.2.0') {
        exclude group: 'com.mapbox.mapboxsdk', module: 'mapbox-sdk-geojson'
        exclude group: 'com.mapbox.mapboxsdk', module: 'mapbox-sdk-turf'
    }
```
everything start work. But i do not know is it right? Also about this no information in read.me. :(
