### ISSUE TITLE
Implementation Issues

### ISSUE THREAD

**Issue by Dandriel** [maplibre/maplibre-navigation-android#62]
**Android API:33**
**Maplibre Navigation SDK version:2.0.0**

### Steps to trigger behavior

 1.Use another app
 2. add dependency 
 3. implementation ('org.maplibre.gl:android-sdk:10.0.2') {
        exclude group: 'com.mapbox.mapboxsdk', module: 'mapbox-sdk-geojson'
        exclude group: 'com.mapbox.mapboxsdk', module: 'mapbox-sdk-turf'
    }
    implementation 'com.github.maplibre:maplibre-navigation-android:2.0.0'
 4. Put code from NavigationUIActivity
 5. Firstly You get "Error inflating class com.mapbox.mapboxsdk.maps.MapView"
 6. After adding to onCreate "Mapbox.getInstance(this)", everything will work
 7. After start navigation you will get "Error inflating class com.mapbox.services.android.navigation.ui.v5.NavigationView".
 P.S. developer-config.xml created
What I do wrong?

### Expected behavior
All work like in example
### Actual behavior
Errors

**Comment by RaheemWilson** [comment]
@Dandriel how did you fix this issue?
