### ISSUE TITLE
[No issue] Info about how to check if arrived or passed the destination

### ISSUE THREAD

**Issue by moiatto** [maplibre/maplibre-navigation-android#69]
In `onMilestoneEvent` I can check when a waypoint is passed with `remainingWaypoints()`. 

How can I check the Destination point? even just to stop navigation.

**Comment by moiatto** [comment]
OK, do you mean `milestone.getIdentifier()` ?

There is a list of identifier values?

**Comment by boldtrn** [comment]
How you want to implement this is your decision, IIRC you have a custom converter from OSMDroid, so this depends on what you add there.

**Comment by moiatto** [comment]
Ok. Thanks

**Comment by moiatto** [comment]
> We use the the onMilestoneEvent in the [Kurviger App](https://play.google.com/store/apps/details?id=com.kurviger.app), there is an arrival milestone, milestones are triggered for Banner Instructions (IIRC).

I tried a lot but without success.

Can you tell me what's wrong?

```
// Custom Milestone for DESTINATION
navigation.addMilestone(new RouteMilestone.Builder()
        .setIdentifier(200)
        .setTrigger(Trigger.all(
                            Trigger.eq(TriggerProperty.LAST_LEG, TriggerProperty.TRUE),
                            Trigger.eq(TriggerProperty.LAST_STEP, TriggerProperty.TRUE)
                    ))
        .build());

// Custom Milestone for WAYPOINT
navigation.addMilestone(new StepMilestone.Builder()
        .setIdentifier(100)
        .setTrigger(Trigger.eq(TriggerProperty.LAST_STEP, TriggerProperty.TRUE))
        .build());
```

**Comment by moiatto** [comment]
I also tried `new BannerInstructionMilestone.Builder()` but it always triggers
