### ISSUE TITLE
Support for Ocean Navigation

### ISSUE THREAD

**Issue by vidhyablrgithub** [maplibre/maplibre-navigation-android#83]
Would like to know if this SDK work on Nautical charts for Ocean navigation. This is required to develop an Android application for boaters to navigate back to HOME from the ocean regions. Please let me know if this SDK can be considered?

**Comment by Fabi755** [comment]
The MapLibre Navigation library only provide the logic for showing the user a turn-by-turn navigation, especially for street drives. The route itself will computed on a server, for example  Mapbox or OSM.

The embedded icons are useful for street turns, I'm not sure if your can re-use them for a boat drive.

This library has a lot of components. You can replace them by your custom logic to solve your problem. I haven't any experience with boat navigation. Maybe you can archive this, if you use this SDK as base and build-up with your own components.

**Comment by boldtrn** [comment]
I agree with @Fabi755, it should be possible to do ship navigation with this library, but this will require some modification on your end. I will close this issue, as it's not really an issue for this library.

**Comment by vidhyablrgithub** [comment]
Like Open Street Map, there s called Open Sea Map..  route computation only
on server side r u saying?

**Comment by boldtrn** [comment]
OpenSeaMap has no route calculation AFAIK. You can calculate the route wherever you like, route calculation is outside of the scope of this repo. You just need to convert the response to a compatible format.
