### ISSUE TITLE
Sample app map is not rendered

### ISSUE THREAD

**Issue by AndrewKisykP** [maplibre/maplibre-navigation-android#85]
<?xml version="1.0" encoding="utf-8"?>
I built your example using the library, but unfortunately I get a blank screen instead of a map. What else do I need to do besides editing developer-config.xml?
<resources>
    
    <string name="base_url" translatable="false">https://api.mapbox.com</string>
    
    <string name="mapbox_access_token" translatable="false">YOUR_MAPBOX_ACCESS_TOKEN_GOES_HERE</string>
    
    <string name="map_style_light" translatable="false"></string>
    
    <string name="map_style_dark" translatable="false"></string>
</resources>
![image](https://github.com/maplibre/maplibre-navigation-android/assets/123394081/426adef0-c83d-44cd-936f-0af8e060c027)

**Comment by Fabi755** [comment]
Do you set a tile provider URL, Like MapTiler?

Are more information in the logs?

**Comment by AndrewKisykP** [comment]
Hi @Fabi755  Im using this map_style_light url 
https://api.maptiler.com/maps/basic-v2/?key=$MY_KEY#0.3/31.27676/43.78558
![image](https://github.com/maplibre/maplibre-navigation-android/assets/123394081/673e8807-1ab3-46f5-b7be-c7b9787f0603)

**Comment by AndrewKisykP** [comment]
i @Fabi755  I managed to fix it, the problem was that the url map tiler contained the coordinates for the preview
![image](https://github.com/maplibre/maplibre-navigation-android/assets/123394081/2b29815a-3368-43dc-aa2d-21fc759b49d0)

**Comment by Fabi755** [comment]
Sounds good 💪 Thanks for share your solution! 💙
