### ISSUE TITLE
Compile Error with Mapbox Maps v10

### ISSUE THREAD

**Issue by iboalali** [maplibre/maplibre-navigation-android#95]
Because the `LocationEngine` package was moved with Mapbox Maps v10, I cannot use any of the MapboxNavigation constructors other then `MapboxNavigation(@NonNull Context context)`

![image](https://github.com/maplibre/maplibre-navigation-android/assets/5447995/95ece161-2ede-4ccd-b423-b5f2cf991c2a)

Even with the constructor without `LocationEngine` as input, I get a compile error
```
error: cannot access LocationEngine
        mapboxNavigation = new MapboxNavigation(requireContext(), options);
                           ^
  class file for com.mapbox.mapboxsdk.location.engine.LocationEngine not found
```

With the default constructor, a `LocationEngine` is being created somehow
![image](https://github.com/maplibre/maplibre-navigation-android/assets/5447995/9c0c0ff2-c6f0-4a3f-902b-f621366a7b73)

**Question:** Is there a plan to allow the `LocationEngine` from Mapbox Maps v10? 

**Android API:** 21 - 33
**Maplibre Navigation SDK version:** 3.0.0

### Steps to trigger behavior

 1. Use `MapboxNavigation(@NonNull Context context, @NonNull MapboxNavigationOptions options)` Constructor
 2. Start compiling
 3. ERROR

### Expected behavior
Compiling with Mapbox Maps v10
### Actual behavior
Compile error with Mapbox Maps v10

**Comment by iboalali** [comment]
Ok, I thought it is compatible with Mapbox Maps. My bad.

Because we Mapbox for Maps and Navigation, but are trying to get away from them (Business decision), and we are looking for alternatives. Right now just for the navigation.

**Comment by boldtrn** [comment]
Supporting Mapbox Maps is not really something we are looking into. You should be able to make this repo work with Mapbox Maps with some effort, we have not removed compatibility on purpose, but we don't care about compatibility either.

**Comment by iboalali** [comment]
Ok, fair.
Btw. I got it to work with Reflection 🙈
